### ISSUE TITLE
Equipo

### ISSUE THREAD

**Issue by ioliasa** [FzrFernando/Ejercicio3Trimestre#1]
Duplicas los atributos, ten mucho cuidado con esto.

**Comment by FzrFernando** [comment]
No se si es lo mismo que me pasaba con alumnos, cuando en el constructor ponía el new HashSet

**Comment by ioliasa** [comment]
si, es el mismo fallo

**Comment by FzrFernando** [comment]
Creo que ya lo he arreglado, si está mal volveré a buscar el error, por eso no cierro todavía el issue

**Comment by ioliasa** [comment]
ok
