### ISSUE TITLE
Historial

### ISSUE THREAD

**Issue by ioliasa** [FzrFernando/Ejercicio3Trimestre#2]
Nunca debes devolver un atributo privado que puedan modificar, es decir las colecciones.

ConsultaDia debes salir cuando la fecha que estás mirando es menor que la que estás buscando

**Comment by FzrFernando** [comment]
Pero consultarDia fue lo que estuvimos hablando de que tenía que ser After no?

**Comment by ioliasa** [comment]
Eso, pero creo que no lo tenías puesto no???

**Comment by FzrFernando** [comment]
Lo tengo puesto en el else if, no sé si es ahí donde debería ir, si lo es cierro el issue ya

**Comment by ioliasa** [comment]
Si, ya está bien
